name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.0.5
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=2.11.0
  - pyarrow=2.0
  - pip:
      - wandb==0.10.31
      - notebook==6.2.0
      - Flask>=2.2.0
